try {
    throw new Error('We have some problem');
} catch(err) {
    
}
